
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN COMMA DEFINITION DIVIDE FOR GENERATOR ID LEFTPH MINUS NUMBER PLUS PRINT RIGTHPH STRING TIMESprogram : stm program\n               | stm\n     stm :  print\n        | assignation\n        | expression\n     print : PRINT LEFTPH expression RIGTHPH\n            | PRINT LEFTPH value RIGTHPH\n     expression : expression operator expression\n                  | value operator value\n                  | value\n     operator : PLUS\n                 | MINUS\n                 | TIMES\n                 | DIVIDE\n    \n        assignation : DEFINITION ID ASSIGN value\n                    | DEFINITION ID ASSIGN expression\n                    | DEFINITION ID ASSIGN generator\n    value : NUMBER\n            | STRING\n            | ID\n\n    generator : GENERATOR LEFTPH NUMBER COMMA NUMBER COMMA expression RIGTHPH FOR ID'
    
_lr_action_items = {'PRINT':([0,2,3,4,5,7,9,10,11,21,24,26,27,28,29,30,40,],[6,6,-3,-4,-5,-10,-20,-18,-19,-8,-9,-6,-7,-10,-16,-17,-21,]),'DEFINITION':([0,2,3,4,5,7,9,10,11,21,24,26,27,28,29,30,40,],[8,8,-3,-4,-5,-10,-20,-18,-19,-8,-9,-6,-7,-10,-16,-17,-21,]),'NUMBER':([0,2,3,4,5,7,9,10,11,13,14,15,16,17,18,19,21,24,25,26,27,28,29,30,32,34,36,40,],[10,10,-3,-4,-5,-10,-20,-18,-19,10,-11,-12,-13,-14,10,10,-8,-9,10,-6,-7,-10,-16,-17,33,35,10,-21,]),'STRING':([0,2,3,4,5,7,9,10,11,13,14,15,16,17,18,19,21,24,25,26,27,28,29,30,36,40,],[11,11,-3,-4,-5,-10,-20,-18,-19,11,-11,-12,-13,-14,11,11,-8,-9,11,-6,-7,-10,-16,-17,11,-21,]),'ID':([0,2,3,4,5,7,8,9,10,11,13,14,15,16,17,18,19,21,24,25,26,27,28,29,30,36,39,40,],[9,9,-3,-4,-5,-10,20,-20,-18,-19,9,-11,-12,-13,-14,9,9,-8,-9,9,-6,-7,-10,-16,-17,9,40,-21,]),'$end':([1,2,3,4,5,7,9,10,11,12,21,24,26,27,28,29,30,40,],[0,-2,-3,-4,-5,-10,-20,-18,-19,-1,-8,-9,-6,-7,-10,-16,-17,-21,]),'PLUS':([5,7,9,10,11,21,22,23,24,28,29,37,],[14,14,-20,-18,-19,14,14,14,-9,14,14,14,]),'MINUS':([5,7,9,10,11,21,22,23,24,28,29,37,],[15,15,-20,-18,-19,15,15,15,-9,15,15,15,]),'TIMES':([5,7,9,10,11,21,22,23,24,28,29,37,],[16,16,-20,-18,-19,16,16,16,-9,16,16,16,]),'DIVIDE':([5,7,9,10,11,21,22,23,24,28,29,37,],[17,17,-20,-18,-19,17,17,17,-9,17,17,17,]),'LEFTPH':([6,31,],[18,32,]),'RIGTHPH':([7,9,10,11,21,22,23,24,37,],[-10,-20,-18,-19,-8,26,27,-9,38,]),'ASSIGN':([20,],[25,]),'GENERATOR':([25,],[31,]),'COMMA':([33,35,],[34,36,]),'FOR':([38,],[39,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,2,],[1,12,]),'stm':([0,2,],[2,2,]),'print':([0,2,],[3,3,]),'assignation':([0,2,],[4,4,]),'expression':([0,2,13,18,25,36,],[5,5,21,22,29,37,]),'value':([0,2,13,18,19,25,36,],[7,7,7,23,24,28,7,]),'operator':([5,7,21,22,23,28,29,37,],[13,19,13,13,19,19,13,13,]),'generator':([25,],[30,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> stm program','program',2,'p_program','parser.py',5),
  ('program -> stm','program',1,'p_program','parser.py',6),
  ('stm -> print','stm',1,'p_stm','parser.py',15),
  ('stm -> assignation','stm',1,'p_stm','parser.py',16),
  ('stm -> expression','stm',1,'p_stm','parser.py',17),
  ('print -> PRINT LEFTPH expression RIGTHPH','print',4,'p_print','parser.py',23),
  ('print -> PRINT LEFTPH value RIGTHPH','print',4,'p_print','parser.py',24),
  ('expression -> expression operator expression','expression',3,'p_expression','parser.py',30),
  ('expression -> value operator value','expression',3,'p_expression','parser.py',31),
  ('expression -> value','expression',1,'p_expression','parser.py',32),
  ('operator -> PLUS','operator',1,'p_operator','parser.py',43),
  ('operator -> MINUS','operator',1,'p_operator','parser.py',44),
  ('operator -> TIMES','operator',1,'p_operator','parser.py',45),
  ('operator -> DIVIDE','operator',1,'p_operator','parser.py',46),
  ('assignation -> DEFINITION ID ASSIGN value','assignation',4,'p_assignation','parser.py',53),
  ('assignation -> DEFINITION ID ASSIGN expression','assignation',4,'p_assignation','parser.py',54),
  ('assignation -> DEFINITION ID ASSIGN generator','assignation',4,'p_assignation','parser.py',55),
  ('value -> NUMBER','value',1,'p_value','parser.py',62),
  ('value -> STRING','value',1,'p_value','parser.py',63),
  ('value -> ID','value',1,'p_value','parser.py',64),
  ('generator -> GENERATOR LEFTPH NUMBER COMMA NUMBER COMMA expression RIGTHPH FOR ID','generator',10,'p_generator','parser.py',71),
]
